language: node_js

node_js:
  - "12"
  - "10"
  - "8"

branches:
  only:
    - master

env:
  - CODECOV_TOKEN=""

before_install:
  - npm i -g npm

script:
  - yarn global add codecov
  - yarn build
  - yarn test

after_success:
  - travis_retry codecov
