language: node_js

node_js:
  - "14"
  - "12"
  - "10"

branches:
  only:
    - master

env:
  - CODECOV_TOKEN="956919f6-f4a7-49e6-8b81-c1c5d657672d"

before_install:
  - npm i -g npm

script:
  - yarn global add codecov
  - yarn build
  - yarn test

after_success:
  - travis_retry codecov
